require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'mutlulugaGidenYol' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'

  pod 'react-native-google-places', :path => '../node_modules/react-native-google-places'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  target 'mutlulugaGidenYolTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'mutlulugaGidenYol-tvOS' do
  # Pods for mutlulugaGidenYol-tvOS

  target 'mutlulugaGidenYol-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
